spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels_db
    username: postgres
    password: parolation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

